# Analysis of the performace of the best configuration with and without elitism

In [1]:
import os, shutil
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
directory = "/Users/franz/Downloads/sudoku_solver-main-4/testing_results/elitism/"

all_file_names = sorted(os.listdir(directory))
try:
    all_file_names.remove(".DS_Store")
except:
    pass

print("There are", len(all_file_names), "csv files in the directory!")

There are 2 csv files in the directory!

In [3]:
tournament__pmx_co__swap_mutation__1000_w_elitism = pd.read_csv(directory + "tournament__pmx_co__swap_mutation__1000_w_elitism.csv")
tournament__pmx_co__swap_mutation__1000_no_elitism = pd.read_csv(directory + "tournament__pmx_co__swap_mutation__1000_no_elitism.csv")

In [4]:
display(tournament__pmx_co__swap_mutation__1000_w_elitism)
print("\n\n\033[1mwith elitism:\033[0m")
print("Average throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__1000_w_elitism["Average_Fitness"].mean(),2))

,Unnamed: 0,R_1,R_2,R_3,R_4,R_5,R_6,R_7,R_8,R_9,...,R_17,R_18,R_19,R_20,R_21,R_22,R_23,R_24,R_25,Average_Fitness
0,easy,253,249,247,250,242,255,254,247,254,...,254,256,253,251,248,249,254,255,256,251.76
1,medium,255,254,258,256,255,256,258,264,258,...,262,255,250,250,260,258,258,246,252,254.60
2,hard,250,260,248,258,251,256,249,245,254,...,247,250,258,254,256,257,251,254,250,253.60

with elitism:
Average throughout all the difficulty levels: 253.32

In [5]:
display(tournament__pmx_co__swap_mutation__1000_no_elitism)
print("\n\n\033[1mwithout elitism:\033[0m")
print("Average throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__1000_no_elitism["Average_Fitness"].mean(),2))

,Unnamed: 0,R_1,R_2,R_3,R_4,R_5,R_6,R_7,R_8,R_9,...,R_17,R_18,R_19,R_20,R_21,R_22,R_23,R_24,R_25,Average_Fitness
0,easy,262,253,249,256,247,250,251,250,252,...,252,246,254,254,250,246,251,255,255,252.64
1,medium,255,254,251,254,251,250,249,254,243,...,251,243,243,256,258,262,244,254,255,251.40
2,hard,256,253,254,256,244,251,256,245,258,...,246,244,253,247,251,250,251,256,243,251.80

without elitism:
Average throughout all the difficulty levels: 251.95