# Analysis of 2 different fitness functions

In [1]:
import os, shutil
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
directory = "/Users/franz/Downloads/sudoku_solver-main-4/testing_results/2_fitness_functions/"

all_file_names = sorted(os.listdir(directory))
try:
    all_file_names.remove(".DS_Store")
except:
    pass

print("There are", len(all_file_names), "csv files in the directory!")

There are 2 csv files in the directory!

In [3]:
tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6 = pd.read_csv(directory + "tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6.csv")
tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6 = pd.read_csv(directory + "tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6.csv")

In [4]:
display(tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6)
print("\n\n\033[1mFitness Function with 243 max:\033[0m")
print("Average fitness score throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6["Average_Fitness"].mean(),4))
print("Average percentage of 243 reached throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6["Average_Fitness"].mean()/243,4))

for i in range(3):
    count = 0
    for element in tournament__pmx_co__swap_mutation__243__20000__co_p__0_7__mu_p__0_6.iloc[i,:].tolist():
        if element == 243:
            count += 1
            
    if i == 0:
        difficulty = "easy"
    elif i == 1:
        difficulty = "medium"
    else:
        difficulty = "hard"
        
    print("Completely solved Sudokus for difficulty level", difficulty + ":", count)

,Unnamed: 0,R_1,R_2,R_3,R_4,R_5,R_6,R_7,R_8,R_9,...,R_17,R_18,R_19,R_20,R_21,R_22,R_23,R_24,R_25,Average_Fitness
0,easy,243,237,241,240,239,241,241,239,239,...,243,238,237,241,239,241,241,239,240,239.88
1,medium,238,236,239,239,241,239,239,236,235,...,241,239,237,235,240,239,241,236,235,238.32
2,hard,241,238,237,239,239,237,237,236,237,...,237,236,239,237,236,238,237,241,241,238.48

Fitness Function with 243 max:
Average fitness score throughout all the difficulty levels: 238.8933
Average percentage of 243 reached throughout all the difficulty levels: 0.9831
Completely solved Sudokus for difficulty level easy: 3
Completely solved Sudokus for difficulty level medium: 1
Completely solved Sudokus for difficulty level hard: 1

In [5]:
display(tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6)
print("\n\n\033[1mFitness Function with 270 max:\033[0m")
print("Average fitness score throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6["Average_Fitness"].mean(),4))
print("Average throughout all the difficulty levels:", np.round(tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6["Average_Fitness"].mean()/270,4))
for i in range(3):
    count = 0
    for element in tournament__pmx_co__swap_mutation__270__20000__co_p__0_7__mu_p__0_6.iloc[i,:].tolist():
        if element == 270:
            count += 1
            
    if i == 0:
        difficulty = "easy"
    elif i == 1:
        difficulty = "medium"
    else:
        difficulty = "hard"
        
    print("Completely solved Sudokus for difficulty level", difficulty + ":", count)

,Unnamed: 0,R_1,R_2,R_3,R_4,R_5,R_6,R_7,R_8,R_9,...,R_17,R_18,R_19,R_20,R_21,R_22,R_23,R_24,R_25,Average_Fitness
0,easy,262,270,262,263,258,259,266,260,266,...,262,266,258,264,262,260,266,262,262,262.56
1,medium,255,262,264,258,260,270,266,256,256,...,264,266,266,262,266,260,262,260,260,261.48
2,hard,262,262,266,262,262,256,258,262,256,...,258,259,262,263,262,255,266,262,257,260.80

Fitness Function with 270 max:
Average fitness score throughout all the difficulty levels: 261.6133
Average throughout all the difficulty levels: 0.9689
Completely solved Sudokus for difficulty level easy: 1
Completely solved Sudokus for difficulty level medium: 1
Completely solved Sudokus for difficulty level hard: 0